#include"algostuff.hpp"
#include<ctime>
using namespace std;

/*
Assigning Generated Values
	void
	generate(ForwardIter beg, ForwardIter end, Func op)
	
	void
	generate_n(OutputIter beg, Size num, Func op)
	
	* generate() assign the values that are generated by a call of op() to 
	  each element in the range [beg,end)
	* generate_n() assigns the values that are generated by al call of op()
	  to the first num elements in the range starting with beg
*/


class IntGenerator{
	private:
		int low,high,diff;
	public:
		IntGenerator(int low=0,int high=numeric_limits<int>::max())
		:high(high),low(low),diff(high-low){}
		
		int operator()(){
			return rand()%diff+low;
		}
};



int main(){
	list<int> coll;
	srand(time(0));
	
	//insert 10 random numbers
	generate_n(back_inserter(coll),10,IntGenerator(10,20));
	PRINT_ELEMENTS(coll);
	
	//overwrite with 10 new random numbers
	generate(coll.begin(),coll.end(),IntGenerator(50,60));
	PRINT_ELEMENTS(coll);


	return 0;
}
